# Generated by Django 5.0.7 on 2024-08-12 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('total_sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_code', models.CharField(max_length=100)),
                ('price_achat', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price_revient', models.DecimalField(decimal_places=2, max_digits=18)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price_ventes', models.DecimalField(decimal_places=2, max_digits=18)),
                ('benefice', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_product_code', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('localistation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unity_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
    ]
